artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: "https://drive.google.com/file/d/1pvm4-AR4CewQBn9qTPcH3g_zhIFcKA5e/view?usp=share_link"
  url_path: "https://drive.google.com/uc?id="
  local_files: data.csv 

data_preprocessing:
  root_dir: artifacts/data_preprocessing
  local_file: data_preprocess.csv

training:
  root_dir: artifacts/training
  test_data: test.csv
  local_model_file: model.pkl
